CREATE TABLE IF NOT EXISTS ideas (
    id CHAR(36) NOT NULL PRIMARY KEY,
    summary TEXT NOT NULL,
    workflow VARCHAR(255) NOT NULL,
    postedBy VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assignees (
    id CHAR(36) NOT NULL PRIMARY KEY,
    idIdea CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (idIdea) REFERENCES ideas(id)
);

CREATE TABLE IF NOT EXISTS ratings (
    id CHAR(36) NOT NULL PRIMARY KEY,
    idIdea CHAR(36) NOT NULL,
    score INTEGER NOT NULL,
    CHECK (score BETWEEN 1 AND 5),
    FOREIGN KEY (idIdea) REFERENCES ideas(id)
);